### ISSUE TITLE
Sketchel to-do

### ISSUE THREAD

**Issue by EnderDev** [sketchel/frontend#29]
## Todo for the release

- [ ] Domain
- [ ] Hosting from OVH
- [ ] i18n
- [ ] Pushbullet
- [ ] Feed
- [ ] Liking Posts
- [ ] User System
- [ ] Follower System
- [ ] Home Page
- [ ] Popular Page
- [ ] Better color picker
- [ ] Follower/Following/Likes List
- [ ] Username changing
- [ ] Editing
- [ ] Search
- [ ] Badges
- [ ] Password Aggression
- [ ] Comment Markdown
- [ ] Add uploading system.
- [ ] API
- [ ] Direct Messaging
- [ ] Security
- [ ] Canvas/Drawing Board
- [ ] Moderation
- [ ] Notifications
